DEVICE_PATH := device/xiaomi/vili

BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_VENDOR_PROPERTY_NAMESPACE := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

include device/xiaomi/sm8350-common/BoardConfigCommon.mk

TARGET_BOOTLOADER_BOARD_NAME := vili
TARGET_OTA_ASSERT_DEVICE := vili

TARGET_CAMERA_OVERRIDE_FORMAT_FROM_RESERVED := true

ODM_MANIFEST_SKUS := vili vilijp
NFC_ESE_MANIFEST := $(DEVICE_PATH)/hidl/nfc_ese.xml
ODM_MANIFEST_VILI_FILES := $(NFC_ESE_MANIFEST)
ODM_MANIFEST_VILIJP_FILES := $(NFC_ESE_MANIFEST)

KERNEL_FRAGMENT_CONFIG := vendor/vili_QGKI.config

BOARD_VENDOR_KERNEL_MODULES += \
    $(KERNEL_MODULES_OUT)/fts_touch_spi.ko \
    $(KERNEL_MODULES_OUT)/hwid.ko \
    $(KERNEL_MODULES_OUT)/msm_drm.ko \
    $(KERNEL_MODULES_OUT)/xiaomi_touch.ko

BOARD_DTBOIMG_PARTITION_SIZE := 25165824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 113254576128

SOONG_CONFIG_xiaomiSm8350Vars_vibrator_use_effect_stream := true

-include vendor/xiaomi/vili/BoardConfigVendor.mk
